# This is a basic workflow to help you get started with Actions

name: Continuous Integration


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Install Dependencies
      run: npm install

    - name: Set who I am
      run: |
        git config --global user.email "vera.wqm@gmail.com"
        git config --global user.name "Vera Wei"
        git config --global url."git@github.com:".insteadOf "https://github.com/"
    # Runs a set of commands using the runners shell
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      # run: npm run deploy
